#!/usr/bin/env bash

source concorde.bash

get <<'EOS'
  usage: prepare name_of_your_dctk
EOS
printf -v usage '%s\n' "$__"

concorde::get_raw <<'EOS'
  Done! Enjoy your new trapper-keeper! If you're happy with your trapper-keeper,
  run:

      rm -rf .git
      git init
      git add .
      git commit -m 'Starting off %s'
      ./bin/%s init

  Made a mistake? Want to make a different trapper-keeper? Run:

      git add .
      git checkout -f

  Thanks for making a trapper-keeper!
EOS
printf -v message '%s\n' "$__"

prepa_main() {
  local name=${1,,}
  local bin
  local completions
  local root

  $(bring '
    dirname
    ln
    mkdir
    readlink
    rm
  ' from concorde.commands)
  root=$($dirname "$($readlink "$BASH_SOURCE")")
  bin=$root/bin
  completions=$root/completions

  put "Preparing your '$name' trapper-keeper!"

  find "$root" -maxdepth 1 -type f -print0 | xargs -0 rm
  $rm "$bin"/dctk
  $ln ../dctk/bin/dctk "$bin/$name"

  $rm "$completions"/dctk.bash
  $ln ../dctk/completions/dctk.bash "$completions/$name".bash

  $rm "$completions"/dctk.zsh
  $ln ../dctk/completions/dctk.zsh "$completions/$name".zsh

  $mkdir "$root/$name"
  printf "$message" "$name" "$name"
}

sourced && return
strict_mode on

put
(( ! $# )) && die "$usage"
prepa_main "$@"
