#!/usr/bin/env bash

[[ -n $_dctk_completions ]] && return
readonly _dctk_completions=loaded

source kzn.bash
initialize_kzn

main() {
  local command=${1:-}
  local command_path

  is_given "$command" || errexit "usage: dctk completions COMMAND [arg1 arg2...]"

  command_path=$(command -v dctk-"$command")
  grep -qi "# provide completions" "$command_path" || return 0
  shift
  exec "$command_path" --complete "$@"
}

return 0 2>/dev/null ||:

strict_mode on
main "$@"
