#!/usr/bin/env bash

[[ -n $_dctk ]] && return
readonly _dctk=loaded

source kzn.bash
initialize_kzn

main() {
  local command=${1:-}
  local command_path
  local libexec

  libexec=$(realpath "$BASH_SOURCE")
  libexec=$(dirname "$libexec")

  case $command in
    "" | "-h" | "--help" )
      exec "$libexec"/dctk-help
      ;;
    * )
      command_path=$libexec/dctk-$command
      is_executable_file "$command_path" || errexit "dctk: no such command '$command'"
      shift
      exec "$command_path" "$@"
      ;;
  esac
}

return 0 2>/dev/null ||:

strict_mode on
main "$@"
