#!/usr/bin/env bash
# Usage: dctk commands
# Summary: List all dctk commands
# Help: This command is mostly used for autocompletion in various shells, and for `dctk help`.
# Also, this command helps find commands that are named the same as potentially builtin shell commands (which, cd, etc)

[[ -n $_dctk_commands ]] && return
readonly _dctk_commands=loaded

source kzn.bash
initialize_kzn

main() {
  local libexec

  libexec=$(realpath "$BASH_SOURCE")
  libexec=$(dirname "$libexec")

  # provide completions
  # shellcheck disable=SC2154
  is_same_as --complete "${1:-}" && { puts "$completions"; exit ;}

  list_commands "$libexec" | uniq | sort
}

list_commands() {
  local libexec=$1
  local command

  shopt -s nullglob
  for command in "$libexec"/*; do
    puts "$(basename "$command")"
  done
}

return 0 2>/dev/null ||:

strict_mode on
main "$@"
