#!/usr/bin/env bash
# Usage: %s commands
# Summary: List all %s commands
# Help: This command is mostly used for autocompletion in various shells, and for `%s help`.

[[ -n $_dctk_commands ]] && return
readonly _dctk_commands=loaded

source kzn.bash

commands_main() {
  local libexec

  libexec=$(realpath "$BASH_SOURCE")
  libexec=$(dirname libexec)

  list_commands libexec | uniq | sort
}

list_commands() {
  # shellcheck disable=SC2034
  local params=( libexec )
  eval "$(passed params "$@")"

  local command

  shopt -s nullglob
  # shellcheck disable=SC2034
  for command in "$libexec"/*; do
    puts "$(basename command)"
  done
}

return 0 2>/dev/null ||:

strict_mode on
commands_main "$@"
