#!/usr/bin/env bash

source kaizen.bash
$(bring head from kaizen.commands)

usage=$'usage: dctk completions COMMAND [arg1 arg2...]\n'

main () {
  local command

  absolute_dirname "$BASH_SOURCE"
  command=$__/$1

  ! completions? "$command" && return
  shift
  exec "$command" --complete "$@"
}

completions? () {
  script? "$1" || return
  $head "$1" | grep -qi "[#] completions: true"
}

script? () {
  [[ $(head --bytes=2 -- "$1") == "#!" ]]
}

sourced? && return
strict_mode on

(( ! $# )) && die "$usage"
main "$@"
