#!/usr/bin/env bash

[[ -n $_dctk_completions ]] && return
readonly _dctk_completions=loaded

source kzn.bash
initialize_kzn

main() {
  local command=${1:-}
  local command_path
  local libexec

  is_given "$command" || errexit "usage: dctk completions COMMAND [arg1 arg2...]"

  libexec=$(realpath "$BASH_SOURCE")
  libexec=$(dirname "$libexec")
  command_path=$libexec/$command

  grep -qi "# provide completions" "$command_path" || return 0
  shift
  exec "$command_path" --complete "$@"
}

return 0 2>/dev/null ||:

strict_mode on
main "$@"
