#!/usr/bin/env bash

source kaizen.bash
$(bring '
  basename
  dirname
' from kaizen.commands)

prog=${_DCTK_PROG:-dctk}
__=$($dirname "$BASH_SOURCE")
absolute_path "$__"/../..
root=$__
completions=$root/completions

get <<'EOS'
  # Load %s automatically by adding
  # the following to %%s:

  eval "$(%s/bin/%s init -)"\n
EOS
printf -v error_message "$__" "$prog" "$root" "$prog"

get <<'EOS'
  for file in %q/*.%s; do
    source "$file"
  done
  unset -v file\n
EOS
shell_format=$__

main () {
  local arg=${1:-}
  local profile
  local shell

  case $arg in
    -|''  ) shell=$($basename "$SHELL") ;;
    *     ) shell=$arg                  ;;
  esac

  case $shell in
    bash  ) profile='~/.bash_profile' ;;
    zsh   ) profile='~/.zshenv'       ;;
    *     ) profile='your profile'    ;;
  esac

  [[ $arg != - ]] && {
    printf -v __ "$error_message" "$profile"
    die "$__" rc=1
  }

  printf 'export PATH+=:%q/bin\n' "$root"
  case $shell in
    bash|zsh ) printf "$shell_format" "$completions" "$shell";;
  esac
}

sourced? && return
strict_mode on
echo

main "$@"
